# Generated by Django 3.0 on 2021-03-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('date_added',)},
        ),
    ]
